# Generated by Django 4.1.4 on 2022-12-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Location',
        ),
        migrations.AddField(
            model_name='comment',
            name='quote',
            field=models.ForeignKey(default='some string', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quotes.quotes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='some string', max_length=240),
        ),
    ]
