# Generated by Django 4.1.4 on 2022-12-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotes',
        ),
    ]
