# Generated by Django 4.1.4 on 2022-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_delete_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
