# Generated by Django 4.1.3 on 2022-12-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='tags',
        ),
    ]
